# Generated by Django 5.1.5 on 2025-03-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallop_app", "0002_usstatetopojson"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="usstatetopojson",
            table="us_states_topo",
        ),
    ]
