# Generated by Django 5.1.5 on 2025-03-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallop_app", "0003_alter_usstatetopojson_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="USDistrictTopojson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topojson", models.JSONField()),
            ],
            options={
                "db_table": "us_districts_topo",
            },
        ),
    ]
