# Generated by Django 5.1.5 on 2025-03-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallop_app", "0004_usdistricttopojson"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CongressionalDistrict",
        ),
        migrations.DeleteModel(
            name="USState",
        ),
        migrations.AddField(
            model_name="congressmembers",
            name="committee_assignments",
            field=models.TextField(blank=True, default="Unknown"),
        ),
    ]
