# Generated by Django 5.1.5 on 2025-03-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallop_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="USStateTopojson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topojson", models.JSONField()),
            ],
            options={
                "db_table": "us_state_topojson",
            },
        ),
    ]
